### ISSUE TITLE
报错: Embedded error: Get "https://chat.openai.com/api/auth/csrf": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by linkedlist771** [xqdoo00o/ChatGPT-to-API#34]
您好，在使用您的项目时发生了如下报错：
```bash
Embedded error: Get "https://chat.openai.com/api/auth/csrf": x509: certificate signed by unknown authority
```
启动命令：
```bash
docker-compose up
```
docker-compose.yaml:
```yaml
version: '3'

services:
  app:
    image: acheong08/chatgpt-to-api # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: TotallySecurePassword
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is <NOT> equired.
      PUID: xxx
    volumes:
      - ./tools/authenticator/accounts.txt:/app/accounts.txt
      - ./tools/authenticator/api_keys.txt:/app/api_keys.txt # 假设您也想挂载这个文件
      - ./access_tokens.json:/app/access_tokens.json # 假

```
